import type { MxActionSheetItem, MxActionSheetOptions, PassThroughProps, Type, MxButtonType, Size, MxCalendarDateConfig, MxCalendarMode, MxListViewItem, MxFilterItemType, MxSelectOption, MxFormLabelPosition, MxFormRule, MxFormValidateError, MxInputType, MxListItem, Justify, MxListViewGroup, MxListViewVirtualItem, MxListViewRefresherStatus, MxPopupDirection, MxQrcodeMode, MxSelectValue, MxSelectDateShortcut, MxSelectSeatItem, MxSelectSeatValue, MxTabbarItem, MxTabsItem, MxTextType, MxToastOptions, MxTreeItem, MxTreeNodeInfo, MxUploadItem } from "./types";
import { type QrcodeOptions } from "./draw";

import type { MxActionSheetProps, MxActionSheetPassThrough } from "./components/mx-action-sheet/props";
import type { MxAvatarProps, MxAvatarPassThrough } from "./components/mx-avatar/props";
import type { MxBackTopProps } from "./components/mx-back-top/props";
import type { MxBadgeProps, MxBadgePassThrough } from "./components/mx-badge/props";
import type { MxBannerProps, MxBannerPassThrough } from "./components/mx-banner/props";
import type { MxButtonProps, MxButtonPassThrough } from "./components/mx-button/props";
import type { MxCalendarProps, MxCalendarPassThrough } from "./components/mx-calendar/props";
import type { MxCalendarSelectProps, MxCalendarSelectPassThrough } from "./components/mx-calendar-select/props";
import type { MxCascaderProps, MxCascaderPassThrough } from "./components/mx-cascader/props";
import type { MxCheckboxProps, MxCheckboxPassThrough } from "./components/mx-checkbox/props";
import type { MxColProps, MxColPassThrough } from "./components/mx-col/props";
import type { MxCollapseProps, MxCollapsePassThrough } from "./components/mx-collapse/props";
import type { MxCountdownProps, MxCountdownPassThrough } from "./components/mx-countdown/props";
import type { MxCropperProps, MxCropperPassThrough } from "./components/mx-cropper/props";
import type { MxDraggableProps, MxDraggablePassThrough } from "./components/mx-draggable/props";
import type { MxFilterBarProps } from "./components/mx-filter-bar/props";
import type { MxFilterItemProps, MxFilterItemPassThrough } from "./components/mx-filter-item/props";
import type { MxFloatViewProps } from "./components/mx-float-view/props";
import type { MxFooterProps, MxFooterPassThrough } from "./components/mx-footer/props";
import type { MxFormProps, MxFormPassThrough } from "./components/mx-form/props";
import type { MxFormItemProps, MxFormItemPassThrough } from "./components/mx-form-item/props";
import type { MxIconProps, MxIconPassThrough } from "./components/mx-icon/props";
import type { MxImageProps, MxImagePassThrough } from "./components/mx-image/props";
import type { MxIndexBarProps, MxIndexBarPassThrough } from "./components/mx-index-bar/props";
import type { MxInputProps, MxInputPassThrough } from "./components/mx-input/props";
import type { MxInputNumberProps, MxInputNumberPassThrough, MxInputNumberValuePassThrough, MxInputNumberOpPassThrough } from "./components/mx-input-number/props";
import type { MxInputOtpProps, MxInputOtpPassThrough } from "./components/mx-input-otp/props";
import type { MxKeyboardCarProps, MxKeyboardCarPassThrough } from "./components/mx-keyboard-car/props";
import type { MxKeyboardNumberProps, MxKeyboardNumberPassThrough } from "./components/mx-keyboard-number/props";
import type { MxKeyboardPasswordProps, MxKeyboardPasswordPassThrough } from "./components/mx-keyboard-password/props";
import type { MxListProps, MxListPassThrough } from "./components/mx-list/props";
import type { MxListItemProps, MxListItemPassThrough } from "./components/mx-list-item/props";
import type { MxListViewProps, MxListViewPassThrough } from "./components/mx-list-view/props";
import type { MxLoadingProps, MxLoadingPassThrough } from "./components/mx-loading/props";
import type { MxLoadmoreProps, MxLoadmorePassThrough } from "./components/mx-loadmore/props";
import type { MxMarqueeProps, MxMarqueePassThrough } from "./components/mx-marquee/props";
import type { MxNoticebarProps, MxNoticebarPassThrough } from "./components/mx-noticebar/props";
import type { MxPageProps } from "./components/mx-page/props";
import type { MxPaginationProps, MxPaginationPassThrough } from "./components/mx-pagination/props";
import type { MxSelectPickerViewProps } from "./components/mx-select-picker-view/props";
import type { MxPopupProps, MxPopupPassThrough, MxPopupHeaderPassThrough } from "./components/mx-popup/props";
import type { MxProgressProps, MxProgressPassThrough } from "./components/mx-progress/props";
import type { MxProgressCircleProps, MxProgressCirclePassThrough } from "./components/mx-progress-circle/props";
import type { MxQrcodeProps } from "./components/mx-qrcode/props";
import type { MxRadioProps, MxRadioPassThrough } from "./components/mx-radio/props";
import type { MxRateProps, MxRatePassThrough } from "./components/mx-rate/props";
import type { MxReadMoreProps, MxReadMorePassThrough } from "./components/mx-read-more/props";
import type { MxRowProps, MxRowPassThrough } from "./components/mx-row/props";
import type { MxSafeAreaProps, MxSafeAreaPassThrough } from "./components/mx-safe-area/props";
import type { MxSelectProps, MxSelectPassThrough } from "./components/mx-select/props";
import type { MxSelectDateProps, MxSelectDatePassThrough } from "./components/mx-select-date/props";
import type { MxSelectSeatProps } from "./components/mx-select-seat/props";
import type { MxSelectTimeProps, MxSelectTimePassThrough } from "./components/mx-select-time/props";
import type { MxSelectTriggerProps, MxSelectTriggerPassThrough } from "./components/mx-select-trigger/props";
import type { MxSignProps, MxSignPassThrough } from "./components/mx-sign/props";
import type { MxSkeletonProps, MxSkeletonPassThrough } from "./components/mx-skeleton/props";
import type { MxSlideVerifyProps, MxSlideVerifyPassThrough } from "./components/mx-slide-verify/props";
import type { MxSliderProps, MxSliderPassThrough } from "./components/mx-slider/props";
import type { MxStickyProps } from "./components/mx-sticky/props";
import type { MxSwitchProps, MxSwitchPassThrough } from "./components/mx-switch/props";
import type { MxTabbarProps, MxTabbarPassThrough } from "./components/mx-tabbar/props";
import type { MxTabsProps, MxTabsPassThrough } from "./components/mx-tabs/props";
import type { MxTagProps, MxTagPassThrough } from "./components/mx-tag/props";
import type { MxTextProps, MxTextPassThrough } from "./components/mx-text/props";
import type { MxTextareaProps, MxTextareaPassThrough } from "./components/mx-textarea/props";
import type { MxTimelineProps, MxTimelinePassThrough } from "./components/mx-timeline/props";
import type { MxTimelineItemProps, MxTimelineItemPassThrough } from "./components/mx-timeline-item/props";
import type { MxToastProps } from "./components/mx-toast/props";
import type { MxTopbarProps, MxTopbarPassThrough } from "./components/mx-topbar/props";
import type { MxTreeProps, MxTreePassThrough } from "./components/mx-tree/props";
import type { MxTreeItemProps, MxTreeItemPassThrough } from "./components/mx-tree-item/props";
import type { MxUploadProps, MxUploadPassThrough } from "./components/mx-upload/props";
import type { MxWaterfallProps, MxWaterfallPassThrough } from "./components/mx-waterfall/props";
import type { MxWatermarkProps, MxWatermarkPassThrough } from "./components/mx-watermark/props";

export {};

// 自动生成的组件全局类型声明
declare module "vue" {
	export interface GlobalComponents {
		"mx-action-sheet": (typeof import('./components/mx-action-sheet/mx-action-sheet.uvue')['default']) & import('vue').DefineComponent<MxActionSheetProps>;
		"mx-avatar": (typeof import('./components/mx-avatar/mx-avatar.uvue')['default']) & import('vue').DefineComponent<MxAvatarProps>;
		"mx-back-top": (typeof import('./components/mx-back-top/mx-back-top.uvue')['default']) & import('vue').DefineComponent<MxBackTopProps>;
		"mx-badge": (typeof import('./components/mx-badge/mx-badge.uvue')['default']) & import('vue').DefineComponent<MxBadgeProps>;
		"mx-banner": (typeof import('./components/mx-banner/mx-banner.uvue')['default']) & import('vue').DefineComponent<MxBannerProps>;
		"mx-button": (typeof import('./components/mx-button/mx-button.uvue')['default']) & import('vue').DefineComponent<MxButtonProps>;
		"mx-calendar": (typeof import('./components/mx-calendar/mx-calendar.uvue')['default']) & import('vue').DefineComponent<MxCalendarProps>;
		"mx-calendar-select": (typeof import('./components/mx-calendar-select/mx-calendar-select.uvue')['default']) & import('vue').DefineComponent<MxCalendarSelectProps>;
		"mx-cascader": (typeof import('./components/mx-cascader/mx-cascader.uvue')['default']) & import('vue').DefineComponent<MxCascaderProps>;
		"mx-checkbox": (typeof import('./components/mx-checkbox/mx-checkbox.uvue')['default']) & import('vue').DefineComponent<MxCheckboxProps>;
		"mx-col": (typeof import('./components/mx-col/mx-col.uvue')['default']) & import('vue').DefineComponent<MxColProps>;
		"mx-collapse": (typeof import('./components/mx-collapse/mx-collapse.uvue')['default']) & import('vue').DefineComponent<MxCollapseProps>;
		"mx-countdown": (typeof import('./components/mx-countdown/mx-countdown.uvue')['default']) & import('vue').DefineComponent<MxCountdownProps>;
		"mx-cropper": (typeof import('./components/mx-cropper/mx-cropper.uvue')['default']) & import('vue').DefineComponent<MxCropperProps>;
		"mx-draggable": (typeof import('./components/mx-draggable/mx-draggable.uvue')['default']) & import('vue').DefineComponent<MxDraggableProps>;
		"mx-filter-bar": (typeof import('./components/mx-filter-bar/mx-filter-bar.uvue')['default']) & import('vue').DefineComponent<MxFilterBarProps>;
		"mx-filter-item": (typeof import('./components/mx-filter-item/mx-filter-item.uvue')['default']) & import('vue').DefineComponent<MxFilterItemProps>;
		"mx-float-view": (typeof import('./components/mx-float-view/mx-float-view.uvue')['default']) & import('vue').DefineComponent<MxFloatViewProps>;
		"mx-footer": (typeof import('./components/mx-footer/mx-footer.uvue')['default']) & import('vue').DefineComponent<MxFooterProps>;
		"mx-form": (typeof import('./components/mx-form/mx-form.uvue')['default']) & import('vue').DefineComponent<MxFormProps>;
		"mx-form-item": (typeof import('./components/mx-form-item/mx-form-item.uvue')['default']) & import('vue').DefineComponent<MxFormItemProps>;
		"mx-icon": (typeof import('./components/mx-icon/mx-icon.uvue')['default']) & import('vue').DefineComponent<MxIconProps>;
		"mx-image": (typeof import('./components/mx-image/mx-image.uvue')['default']) & import('vue').DefineComponent<MxImageProps>;
		"mx-index-bar": (typeof import('./components/mx-index-bar/mx-index-bar.uvue')['default']) & import('vue').DefineComponent<MxIndexBarProps>;
		"mx-input": (typeof import('./components/mx-input/mx-input.uvue')['default']) & import('vue').DefineComponent<MxInputProps>;
		"mx-input-number": (typeof import('./components/mx-input-number/mx-input-number.uvue')['default']) & import('vue').DefineComponent<MxInputNumberProps>;
		"mx-input-otp": (typeof import('./components/mx-input-otp/mx-input-otp.uvue')['default']) & import('vue').DefineComponent<MxInputOtpProps>;
		"mx-keyboard-car": (typeof import('./components/mx-keyboard-car/mx-keyboard-car.uvue')['default']) & import('vue').DefineComponent<MxKeyboardCarProps>;
		"mx-keyboard-number": (typeof import('./components/mx-keyboard-number/mx-keyboard-number.uvue')['default']) & import('vue').DefineComponent<MxKeyboardNumberProps>;
		"mx-keyboard-password": (typeof import('./components/mx-keyboard-password/mx-keyboard-password.uvue')['default']) & import('vue').DefineComponent<MxKeyboardPasswordProps>;
		"mx-list": (typeof import('./components/mx-list/mx-list.uvue')['default']) & import('vue').DefineComponent<MxListProps>;
		"mx-list-item": (typeof import('./components/mx-list-item/mx-list-item.uvue')['default']) & import('vue').DefineComponent<MxListItemProps>;
		"mx-list-view": (typeof import('./components/mx-list-view/mx-list-view.uvue')['default']) & import('vue').DefineComponent<MxListViewProps>;
		"mx-loading": (typeof import('./components/mx-loading/mx-loading.uvue')['default']) & import('vue').DefineComponent<MxLoadingProps>;
		"mx-loadmore": (typeof import('./components/mx-loadmore/mx-loadmore.uvue')['default']) & import('vue').DefineComponent<MxLoadmoreProps>;
		"mx-marquee": (typeof import('./components/mx-marquee/mx-marquee.uvue')['default']) & import('vue').DefineComponent<MxMarqueeProps>;
		"mx-noticebar": (typeof import('./components/mx-noticebar/mx-noticebar.uvue')['default']) & import('vue').DefineComponent<MxNoticebarProps>;
		"mx-page": (typeof import('./components/mx-page/mx-page.uvue')['default']) & import('vue').DefineComponent<MxPageProps>;
		"mx-pagination": (typeof import('./components/mx-pagination/mx-pagination.uvue')['default']) & import('vue').DefineComponent<MxPaginationProps>;
		"mx-select-picker-view": (typeof import('./components/mx-select-picker-view/mx-select-picker-view.uvue')['default']) & import('vue').DefineComponent<MxSelectPickerViewProps>;
		"mx-popup": (typeof import('./components/mx-popup/mx-popup.uvue')['default']) & import('vue').DefineComponent<MxPopupProps>;
		"mx-progress": (typeof import('./components/mx-progress/mx-progress.uvue')['default']) & import('vue').DefineComponent<MxProgressProps>;
		"mx-progress-circle": (typeof import('./components/mx-progress-circle/mx-progress-circle.uvue')['default']) & import('vue').DefineComponent<MxProgressCircleProps>;
		"mx-qrcode": (typeof import('./components/mx-qrcode/mx-qrcode.uvue')['default']) & import('vue').DefineComponent<MxQrcodeProps>;
		"mx-radio": (typeof import('./components/mx-radio/mx-radio.uvue')['default']) & import('vue').DefineComponent<MxRadioProps>;
		"mx-rate": (typeof import('./components/mx-rate/mx-rate.uvue')['default']) & import('vue').DefineComponent<MxRateProps>;
		"mx-read-more": (typeof import('./components/mx-read-more/mx-read-more.uvue')['default']) & import('vue').DefineComponent<MxReadMoreProps>;
		"mx-row": (typeof import('./components/mx-row/mx-row.uvue')['default']) & import('vue').DefineComponent<MxRowProps>;
		"mx-safe-area": (typeof import('./components/mx-safe-area/mx-safe-area.uvue')['default']) & import('vue').DefineComponent<MxSafeAreaProps>;
		"mx-select": (typeof import('./components/mx-select/mx-select.uvue')['default']) & import('vue').DefineComponent<MxSelectProps>;
		"mx-select-date": (typeof import('./components/mx-select-date/mx-select-date.uvue')['default']) & import('vue').DefineComponent<MxSelectDateProps>;
		"mx-select-seat": (typeof import('./components/mx-select-seat/mx-select-seat.uvue')['default']) & import('vue').DefineComponent<MxSelectSeatProps>;
		"mx-select-time": (typeof import('./components/mx-select-time/mx-select-time.uvue')['default']) & import('vue').DefineComponent<MxSelectTimeProps>;
		"mx-select-trigger": (typeof import('./components/mx-select-trigger/mx-select-trigger.uvue')['default']) & import('vue').DefineComponent<MxSelectTriggerProps>;
		"mx-sign": (typeof import('./components/mx-sign/mx-sign.uvue')['default']) & import('vue').DefineComponent<MxSignProps>;
		"mx-skeleton": (typeof import('./components/mx-skeleton/mx-skeleton.uvue')['default']) & import('vue').DefineComponent<MxSkeletonProps>;
		"mx-slide-verify": (typeof import('./components/mx-slide-verify/mx-slide-verify.uvue')['default']) & import('vue').DefineComponent<MxSlideVerifyProps>;
		"mx-slider": (typeof import('./components/mx-slider/mx-slider.uvue')['default']) & import('vue').DefineComponent<MxSliderProps>;
		"mx-sticky": (typeof import('./components/mx-sticky/mx-sticky.uvue')['default']) & import('vue').DefineComponent<MxStickyProps>;
		"mx-switch": (typeof import('./components/mx-switch/mx-switch.uvue')['default']) & import('vue').DefineComponent<MxSwitchProps>;
		"mx-tabbar": (typeof import('./components/mx-tabbar/mx-tabbar.uvue')['default']) & import('vue').DefineComponent<MxTabbarProps>;
		"mx-tabs": (typeof import('./components/mx-tabs/mx-tabs.uvue')['default']) & import('vue').DefineComponent<MxTabsProps>;
		"mx-tag": (typeof import('./components/mx-tag/mx-tag.uvue')['default']) & import('vue').DefineComponent<MxTagProps>;
		"mx-text": (typeof import('./components/mx-text/mx-text.uvue')['default']) & import('vue').DefineComponent<MxTextProps>;
		"mx-textarea": (typeof import('./components/mx-textarea/mx-textarea.uvue')['default']) & import('vue').DefineComponent<MxTextareaProps>;
		"mx-timeline": (typeof import('./components/mx-timeline/mx-timeline.uvue')['default']) & import('vue').DefineComponent<MxTimelineProps>;
		"mx-timeline-item": (typeof import('./components/mx-timeline-item/mx-timeline-item.uvue')['default']) & import('vue').DefineComponent<MxTimelineItemProps>;
		"mx-toast": (typeof import('./components/mx-toast/mx-toast.uvue')['default']) & import('vue').DefineComponent<MxToastProps>;
		"mx-topbar": (typeof import('./components/mx-topbar/mx-topbar.uvue')['default']) & import('vue').DefineComponent<MxTopbarProps>;
		"mx-tree": (typeof import('./components/mx-tree/mx-tree.uvue')['default']) & import('vue').DefineComponent<MxTreeProps>;
		"mx-tree-item": (typeof import('./components/mx-tree-item/mx-tree-item.uvue')['default']) & import('vue').DefineComponent<MxTreeItemProps>;
		"mx-upload": (typeof import('./components/mx-upload/mx-upload.uvue')['default']) & import('vue').DefineComponent<MxUploadProps>;
		"mx-waterfall": (typeof import('./components/mx-waterfall/mx-waterfall.uvue')['default']) & import('vue').DefineComponent<MxWaterfallProps>;
		"mx-watermark": (typeof import('./components/mx-watermark/mx-watermark.uvue')['default']) & import('vue').DefineComponent<MxWatermarkProps>;
	}
}
